# Generated by Django 2.1 on 2018-08-27 11:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(max_length=1000), default=list, size=None),
        ),
    ]
