# Generated by Django 2.1 on 2018-08-27 11:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20180827_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='members',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=list),
        ),
    ]
