# Generated by Django 2.1 on 2018-08-27 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainApp', '0003_auto_20180827_1143'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupChatMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='groupchat',
            name='members',
        ),
        migrations.AddField(
            model_name='groupchatmember',
            name='chat',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainApp.GroupChat'),
        ),
        migrations.AddField(
            model_name='groupchatmember',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
