# Generated by Django 2.1 on 2018-08-31 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0008_auto_20180831_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupchat',
            name='group_name',
            field=models.CharField(blank=True, default='', max_length=25),
        ),
    ]
